package com.epicodus.eventmanager;

import android.app.Activity;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.TextView;

import java.util.List;

//to do - delete this event List
public class EventList extends ArrayAdapter<Event> {
    private Activity context;
    private List<Event> eventList;

    public EventList(Activity context, List<Event> eventList){
        super(context,R.layout.list_layout, eventList);

        this.context = context;
        this.eventList = eventList;
    }

    @NonNull
    @Override
    public View getView(int position,View convertView, ViewGroup parent) {
        //return super.getView(position, convertView, parent);//need to delete this autogenerated statement.
        LayoutInflater inflater = context.getLayoutInflater();

        View listViewItem = inflater.inflate(R.layout.list_layout, null, true);

        TextView tvName = (TextView) listViewItem.findViewById(R.id.tvName);
        TextView tvType = (TextView) listViewItem.findViewById(R.id.tvType);
        TextView tvDate = (TextView) listViewItem.findViewById(R.id.tvDate);
        TextView tvTime = (TextView) listViewItem.findViewById(R.id.tvTime);
        TextView tvAddress = (TextView) listViewItem.findViewById(R.id.tvAddress);

        Event event = eventList.get(position);

        tvName.setText(event.getName());
        tvType.setText(event.getType());
        tvDate.setText(event.getDate());
        tvTime.setText(event.getTime());
        tvAddress.setText(event.getAddress());

        return listViewItem;

    }
}
